spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taotao?characterEncoding=utf8
    username: root
    password: root
    # 不加就会报找不到com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver